### ISSUE TITLE
Deploying a broken contract works

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-sidecar#97]
I'm not sure if this should go here or in `stacks-transactions-js`, but there is an error from the node that comes up when I deploy a contract that has some broken element in it:

```
[devenv:deploy] stacks-blockchain_1  | ERROR [1589151877.211] [src/chainstate/stacks/db/transactions.rs:582] Runtime error in contract analysis for ST20R8C77HWT8CWSQZYYZZTNH8FK675AW38260VHX.hello-world-contract: Parse(ParseError { err: FailedParsingRemainder("\'true)\n  )\n)\n(define-public (get-stream\n    (stream-id uint)\n  )\n  (\n    ok\n    (unwrap-panic\n      (map-get? streams (tuple (id stream-id)))\n    )\n  )\n)"), pre_expressions: None, diagnostic: Diagnostic { level: Error, message: "Failed to lex input remainder: \'\'true)\n  )\n)\n(define-public (get-stream\n    (stream-id uint)\n  )\n  (\n    ok\n    (unwrap-panic\n      (map-get? streams (tuple (id stream-id)))\n    )\n  )\n)\'", spans: [], suggestion: None } })
[dev] Smart contract deployed: ST20R8C77HWT8CWSQZYYZZTNH8FK675AW38260VHX.hello-world-contract
```

Is this expected behavior, or should we be capturing broken contracts?

**Comment by zone117x** [comment]
This contract deployment transaction is well formed and mined into the block, but will have a `"tx_status":"failed"` flag (in the sidecar API tx response) because of that Clarity runtime error. 

I don't think the error details like what you see in the node log are propagated anywhere. The failure reason seems like something we should show in the explorer. 

I don't think a verbose error message could be easily passed through, but it maybe an status code indicating a Clarity parsing failure?

**Comment by zone117x** [comment]
@aulneau FYI -- the blockchain team is aiming to add error reason data next sprint. For now, the best the front-end can do is check the `tx_status` flag for `failed` and display a generic error
